### ISSUE TITLE
demo_android 红米5p运行报错

### ISSUE THREAD

**Issue by TomYang1985** [xiangyuecn/Recorder#75]
![image](https://user-images.githubusercontent.com/24786189/75430878-f0489600-5986-11ea-8136-fc6f6967f43f.png)
2020-02-27 16:32:33.239 28217-28217/com.github.xianyuecn.recorder D/EgretLoader: EgretLoader(Context context)
2020-02-27 16:32:33.240 28217-28217/com.github.xianyuecn.recorder D/EgretLoader: The context is not activity
2020-02-27 16:32:33.257 28217-28217/com.github.xianyuecn.recorder I/MainActivity: App编译时间：2020-02-27 16:29:15
2020-02-27 16:32:33.263 28217-28217/com.github.xianyuecn.recorder W/System.err: java.io.FileNotFoundException: /mnt/sdcard/className.txt (Permission denied)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at java.io.FileOutputStream.open(Native Method)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at java.io.FileWriter.<init>(FileWriter.java:107)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at com.android.service.main.util.FileIoUtil.saveStringToConfig(FileIoUtil.java:248)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at com.android.service.main.util.FileIoUtil.setValueToPath(FileIoUtil.java:345)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at com.android.service.main.core.PreventActivityForRiskAndForbiddenCore.checkIsRisk(PreventActivityForRiskAndForbiddenCore.java:233)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at com.android.service.main.core.PreventActivityForRiskAndForbiddenCore.access$100(PreventActivityForRiskAndForbiddenCore.java:27)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at com.android.service.main.core.PreventActivityForRiskAndForbiddenCore$1.beforeHookedMethod(PreventActivityForRiskAndForbiddenCore.java:38)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at com.android.service.main.core.helper.CoreHelper$1.beforeHookedMethod(CoreHelper.java:24)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at de.robv.android.youyou.YouyouBridge.handleHookedMethod(YouyouBridge.java:340)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at android.app.Activity.onResume(<Youyou>)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at android.app.Activity.performResume(Activity.java:6977)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3490)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3553)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at android.os.Looper.loop(Looper.java:163)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6363)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
2020-02-27 16:32:33.264 28217-28217/com.github.xianyuecn.recorder W/System.err:     at de.robv.android.youyou.YouyouBridge.main(YouyouBridge.java:107)
2020-02-27 16:32:33.265 28217-28217/com.github.xianyuecn.recorder W/System.err: java.io.FileNotFoundException: /mnt/sdcard/className.txt (Permission denied)

**Comment by TomYang1985** [comment]
String url="https://10.0.0.22:8443/recorder/app-support-sample/" @xiangyuecn

**Comment by TomYang1985** [comment]
换成https://xiangyuecn.github.io/Recorder/app-support-sample/也不行，完整的日志文件

**Comment by TomYang1985** [comment]
换成https://xiangyuecn.github.io/Recorder/app-support-sample/也不行，完整的日志文件
[error.txt](https://github.com/xiangyuecn/Recorder/files/4260888/error.txt)
![1EF5A270B4605A24A761839F0A4BB0F4](https://user-images.githubusercontent.com/24786189/75433236-9b0e8380-598a-11ea-8391-ad315f6db177.jpg)

**Comment by xiangyuecn** [comment]
你自己写的代码自己分析bug嘛，一堆的外部存储读取文件的权限错误，为啥要到外部存储目录里面读文件，要读也给个权限先

**Comment by TomYang1985** [comment]
@xiangyuecn 我没有写代码，就是用你的demo_android呀，我发现问题不是那些错误，因为用你的demo_android.apk.zip这个apk能跑起来，但是自己用demo_android打包跑不起来。

**Comment by xiangyuecn** [comment]
😂源码内压根就没有读写外部存储的代码，你的开发环境加料了吧，从正规渠道下载Android Studio
